language: java

jdk: openjdk8

sudo: required
services:
  - docker

script: 
  - mvn clean package

env:
  HEROKU_APP_NAME: amaro-challenge
 
deploy:
 provider: heroku
 api-key: 
  secure: SYxLm+zxQflAfFqjWhlDbk33KGsbgq3y6cPRLOPxj+F7ieiIWRvPbJ+6yiMvC0x5icFMF+6LzmYQvJnvXgBeWdC2N8xUZEpOtb4xUWBcHOEybOU/Bf/1/DRFUmLn/TgMyRnBL1+0tILt2K4JVAWut+Mazbr8GHhH+qg2gTNNcklRoVrvmSLiE4PaaHwOvOYUywSmD3CTjpb48RnaUa03d81QMcyXimXXqQQGF05Hz46eTOCB1kacA0Yv3lUVk8YpHCr1OqG/tzVa+5rRcWYzZujy0L1u6uUkhuqW/XKLc0NGyg+LGbNflc2jDxtSpmGfIzyl7/LC3H/WfkQ8V4Asq32ZzvWtIlKu5Ln+XRUyB71GAvb9sR2K5tfptl2e0FBz1ZxZTzidfYGowxVeFnJ13X/3LUhlvVU20OiadxtwuIbnOV4TNIIvbae3mOOpIjBrrvb5VWxK4yCPyOdor5fhaZmmSul/oNRKvnGywKmMoI8OBw0xNP0VqwPEYAWoOUaudB64wLBVj/A1SA9LTD4ZCv7+re1OsiIZlnqdQ9iVW8eKf3OBD1lhe71FJ505vLPuStQRtPDDVL30zVB8Hb/AxZV4fSlzQ/cNUf7ijljv1ycmgFrhqD/LtvZhFPtRcbur+GAif9JlCrwfjJkePFTcpLMFSMFfnz3Oi8DVi3SZZQ4=
 app: $HEROKU_APP_NAME
 
 before_install:
  - chmod +x mvnw