language: java

jdk: openjdk8

sudo: required
services:
  - docker

script: 
  - mvn clean package

env:
  HEROKU_APP_NAME: amaro-challenge
 
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: $HEROKU_APP_NAME
 
 before_install:
  - chmod +x mvnw