/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.12).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package amaro.backend.challenge.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import amaro.backend.challenge.model.ApiErrorResponse;
import amaro.backend.challenge.model.Product;
import amaro.backend.challenge.model.ProductResponse;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-03-26T01:08:13.280Z")

@Api(value = "tagsVector", description = "the tagsVector API", tags = {"TagsVector"})
@RequestMapping(value = "/similarity")
public interface TagsVectorApi {

    @ApiOperation(value = "Creates characteristics tags for each one of the available products in the input payload", nickname = "createCharacteristicsTags", notes = "", response = ProductResponse.class, responseContainer = "List", tags={ "TagsVector", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = ProductResponse.class, responseContainer = "List"),
        @ApiResponse(code = 500, message = "Internal server error", response = ApiErrorResponse.class) })
    @RequestMapping(value = "/tagsVector",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<List<ProductResponse>> createCharacteristicsTags(@ApiParam(value = "An array of available products" ,required=true )  @Valid @RequestBody List<Product> body);

}
